### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by fayazara** [Johann-S/bs-stepper#11]
Error at index.js file at line 51. Which breaks the functioning of the plugin.

Example [here](https://hastebin.com/uticosawuj.xml)

**Comment by Johann-S** [comment]
Hi @fayazara,

You're right but that's because you use the HTML markup from the `master` branch which is not released currently.

So please refer to this markup: https://github.com/Johann-S/bs-stepper/tree/v1.2.1#how-to-use-it

I fixed your problem on this CodePen: https://codepen.io/Johann-S/pen/oaJZaz

And I'll update our documentation to avoid this kind of issue, thanks for reporting it ! 👍

**Comment by Johann-S** [comment]
Fixed by: https://github.com/Johann-S/bs-stepper/commit/757445f543359703b6b3bb060e2702c99c6b6ec4

**Comment by rahimimo** [comment]
I still get it using the codepen codes.
