### ISSUE TITLE
bs_stepper_1.default is not a constructor

### ISSUE THREAD

**Issue by viniciuscst** [Johann-S/bs-stepper#54]
I get the following error, when i tried use the example to angular.

`ERROR TypeError: bs_stepper_1.default is not a constructor
    at PropostaUpdateComponent.ngOnInit (proposta-update.component.ts?7d8b:68)
    at checkAndUpdateDirectiveInline (core.js?09c9:19327)
    at checkAndUpdateNodeInline (core.js?09c9:27585)
    at checkAndUpdateNode (core.js?09c9:27547)
    at debugCheckAndUpdateNode (core.js?09c9:28181)
    at debugCheckDirectivesFn (core.js?09c9:28141)
    at Object.eval [as updateDirectives] (PropostaUpdateComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js?09c9:28133)
    at checkAndUpdateView (core.js?09c9:27529)
    at callViewAction (core.js?09c9:27770)`

**Comment by Johann-S** [comment]
Hi @viniciuscst,

Can you include a live demo of the problem ? You can create a reduced test case via [Stackblitz](https://stackblitz.com/) and report back with your link.

**Comment by sickDevelopers** [comment]
Hello, first of all thank you for your work on this.

Sorry if I join the conversation late but I just faced the same issued and managed to solve it somehow.

Just to throw on the table more details:
- angular version: 4.4.6
- typescript version: 2.3.4
- same code as in the example you gave

My thought on this is that it has something to do with esModuleInterop compiler option. Here is my (dirty but working) solution:

1) added ```esModuleInterop": true``` to compilerOptions in tsconfig.json
2) instead of 
```
import Stepper from "bs-stepper";
```
I used 
```
declare function require(name:string);
const Stepper = require('bs-stepper');
```
( the ```declare``` line is because of complaining typescript compiler)

3) changed ```private stepper: Stepper``` to ```private stepper:any```

Doing so, you loose Stepper typings but you make the constructor work.

I'm no typescript expert so I actually don't know why this is working, hope it helps on solving the issue.

**Comment by VergilSkye** [comment]
> Hello, first of all thank you for your work on this.
> 
> Sorry if I join the conversation late but I just faced the same issue and managed to solve it somehow.
> 
> Just to throw on the table more details:
> 
>     * angular version: 4.4.6
> 
>     * typescript version: 2.3.4
> 
>     * same code as in the example you gave
> 
> 
> My thought on this is that it has something to do with esModuleInterop compiler option. Here is my (dirty but working) solution:
> 
>     1. added `esModuleInterop": true` to compilerOptions in tsconfig.json
> 
>     2. instead of
> 
> 
> ```
> import Stepper from "bs-stepper";
> ```
> 
> I used
> 
> ```
> declare function require(name:string);
> const Stepper = require('bs-stepper');
> ```
> 
> ( the `declare` line is because of complaining typescript compiler)
> 
>     1. changed `private stepper: Stepper` to `private stepper:any`
> 
> 
> Doing so, you loose Stepper typings but you make the constructor work.
> 
> I'm no typescript expert so I actually don't know why this is working, hope it helps on solving the issue.

Thanks so much, this help me a lot!
